apiVersion: apps/v1
kind: Deployment
metadata:
  name: cycling-blog-app
  namespace: golang-app
  labels:
    app: cycling-blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cycling-blog-app
  template:
    metadata:
      labels:
        app: cycling-blog-app
    spec:
      containers:
      - name: cycling-blog-app
        image: jackstock8904/cycling-blog:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          protocol: TCP
          