kind: Service
apiVersion: v1
metadata:
  name: cycling-blog-service
  namespace: golang-app
spec:
  selector:
    app: cycling-blog-app
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 8080
      