apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: jacksapp-dev
data:
  auth: amFjazokYXByMSRUNE52Q2t4MCRQdzJPcVZkbnU4bmxUUmsxdGpNTkExCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
  namespace: jacksapp-dev
type: Opaque
data:
  connect: Y3ljbGluZy1ibG9nLWRiLXNlcnZpY2U6NTQzMjpjeWNsaW5nYmxvZzpkZW1vdXNlcjpQNDU1dzByZA==
  hostname: Y3ljbGluZy1ibG9nLWRi
  username: ZGVtb3VzZXI=
  password: UDQ1NXcwcmQ=
  db_name: Y3ljbGluZ2Jsb2c=
  port: NTQzMg==



