apiVersion: batch/v1
kind: Job
metadata:
  metadata:
  name: cycling-blog-app-insert
  namespace: jacksapp-dev
  labels: 
    app: cycling-blog-app
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        image: bitnami/postgresql:latest
        command: ['sh', '-c', 
          'until pg_isready -h postgres -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: cycling-blog-app
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/jacksapp-dev-ecr:2.0
        imagePullPolicy: Always
        command: ["psql"]
        args: ["-h", "$(CYCLING_BLOG_DB_SERVICE_SERVICE_HOST)", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-w", "-a", "-f", "sql/table_insert.sql"]
        env:
        - name: PGPASSFILE
          valueFrom: 
            secretKeyRef:
              name: pgpass
              key: connect
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: db_name
      restartPolicy: Never