apiVersion: apps/v1
kind: Deployment
metadata:
  name: cycling-blog-db
  namespace: golang-app
  labels: 
    app: cycling-blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cycling-blog-db
  template:
    metadata:
      labels:
        app: cycling-blog-db
    spec: 
      containers:
      - name: cycling-blog-db
        image: postgres:13-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: demouser
        - name: POSTGRES_PASSWORD
          value: P455w0rd
        - name: POSTGRES_DB
          value: cyclingblog
        - name: HOSTNAME
          value: cycling-blog-db

