# Declare variables to be passed into your templates.
namespace: [name of the namespace to be deployed to]

annotations:
  hookDeletePolicy: hook-succeeded ## used for jobs to delete after success deployment
  setIdentifier: [<ingress name>-<namespace name>-green] ## used for ingress 
app_service:
  name: [application service name]
  ports:
    name: [protocol name]
    protocol: [TCP/]
    port: [port number]

ingress:
  enabled: true
  name: [ingress name]
  hosts:
  - host: [application frontend address]
    secretName: [certificate secret name]
  path: /
  serviceName: [application service name]
  servicePort: [application port number]

app_deployment:
  replicas: [number of pods]
  app: [name of application]
  template:
    containers:
      image: [image address]
      imagePullPolicy: [Always/]
      resources:
        requests:
          memory: [min pod memory]
          cpu: [min pod cpu]
        limits:
          memory: [max pod memory]
          cpu: [max pod cpu]
      ports:
      - containerPort: [application port number]