apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cycling_blog_db_create.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.cycling_blog_db_create.app }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": {{ .Values.annotations.hookDeletePolicy }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.cycling_blog_db_create.app }}
        image: {{ .Values.app_deployment.template.containers.image }}
        imagePullPolicy: {{ .Values.cycling_blog_db_create.template.containers.imagePullPolicy }}
        command: ["psql"]
        args: ["-h", "$(CYCLING_BLOG_DB_SERVICE_SERVICE_HOST)", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-w", "-a", "-f", "sql/create_table.sql"]
        env:
        {{- range .Values.db_env }}
        - name: {{ .name }}
          valueFrom: 
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .key }}
        {{- end }}
      restartPolicy: {{ .Values.cycling_blog_db_create.template.restartPolicy }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cycling_blog_db_insert.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.cycling_blog_db_insert.app }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": {{ .Values.annotations.hookDeletePolicy }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.cycling_blog_db_insert.app }}
        image: {{ .Values.app_deployment.template.containers.image }}
        imagePullPolicy: {{ .Values.cycling_blog_db_insert.template.containers.imagePullPolicy }}
        command: ["psql"]
        args: ["-h", "$(CYCLING_BLOG_DB_SERVICE_SERVICE_HOST)", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-w", "-a", "-f", "sql/table_insert.sql"]
        env:
        {{- range .Values.db_env }}
        - name: {{ .name }}
          valueFrom: 
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .key }}
        {{- end }}
      restartPolicy: {{ .Values.cycling_blog_db_insert.template.restartPolicy }}