{{- $envRDS := .Values.envRDS -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app_service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_deployment.app }}
spec:
  ports:
  - name: {{ .Values.app_service.ports.name }}
    protocol: {{ .Values.app_service.ports.protocol }}
    port: {{ .Values.app_service.ports.port }}
    targetPort: {{ .Values.app_service.ports.port }}
  selector:
    app: {{ .Values.app_deployment.app }}
---
{{- if eq $envRDS true -}}
kind: Service
apiVersion: v1
metadata:
 name: {{ .Values.db_service.name }}
 namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: 
    valueFrom:
      secretKeyRef:
        name: {{ .Values.db_service.secretName }}
        key: {{ .Values.db_service.key }}
{{- else if eq $envRDS false -}}
kind: Service
apiVersion: v1
metadata:
 name: {{ .Values.db_service.name }}
 namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.db_service.ports.name }}
    protocol: {{ .Values.db_service.ports.protocol }}
    port: {{ .Values.db_service.ports.port }}
    targetPort: {{ .Values.db_service.ports.port }}
  selector:
    app: {{ .Values.db_deployment.app }}
{{- end }}
