apiVersion: batch/v1
kind: Job
metadata:
  name: cycling-blog-app-create
  namespace: jacksapp-dev
  labels: 
    app: cycling-blog-app
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: cycling-blog-app
        image: jackstock8904/cycling-blog:latest
        imagePullPolicy: Always
        command: ["psql"]
        args: ["-h", "$(CYCLING_BLOG_DB_SERVICE_SERVICE_HOST)", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)", "-w", "-a", "-f", "sql/create_table.sql"]
        env:
        - name: PGPASSFILE
          valueFrom: 
            secretKeyRef:
              name: pgpass
              key: connect
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pgpass
              key: db_name
      restartPolicy: Never