apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: jacksapp-dev
data:
  auth: {{ .Values.secret.data.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
  namespace: jacksapp-dev
type: Opaque
data:
  connect: {{ .Values.secret.data.connect }}
  hostname: {{ .Values.secret.data.hostname }}
  username: {{ .Values.secret.data.username }}
  password: {{ .Values.secret.data.password }}
  db_name: {{ .Values.secret.data.dbname }}
  port: {{ .Values.secret.data.port }}



