# Declare variables to be passed into your templates.
namespace: jacksapp-dev

app_service:
  name: cycling-blog-app-service
  ports:
    name: http
    protocol: TCP
    port: 8080

db_service:
  name: cycling-blog-db-service
  ports:
    name: db
    protocol: TCP
    port: 5432

ingress:
  enabled: true
  name: jackstockley-helloworld-ingress
  annotations:
    ingressClasslass: nginx
    setIdentifier: jackstockley-helloworld-ingress-jacksapp-dev-green
    awsWeight: "100"
  tls:
    hosts:
    - host_1: jackstockley-helloworld.apps.live.cloud-platform.service.justice.gov.uk
    - host_2: jacksapp-devs.service.justice.gov.uk
      secretName: jacksapp-dev-certificate
    rules:
      http:
        paths:
        - path: /
          backend:
            serviceName: cycling-blog-app-service
            servicePort: 8080

db_deployment:
  replicas: 1
  app: cycling-blog-db
  template:
    containers:
      image: bitnami/postgresql:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      ports:
      - containerPort: 5432

app_deployment:
  replicas: 1
  app: cycling-blog-app
  template:
    containers:
      image: ${ECR_URL}:${IMAGE_TAG}
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 8080
      
