name: docker images

on:
  push:
    tags:
      - "*"

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.0.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: jackstockley89/golangwebpage
          tag_with_ref: true
