name: Startup EKS Sandbox
on:
  push

jobs:
  rbac-permissions-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@master

      - name: Output all changes to a file
        run: |
          env
