name: pint

on:
  pull_request:
    paths:
    - kubectl_deploy/*/*promethus.yaml
    - kubectl_deploy/*/*promethus.yml
  workflow_dispatch:

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Run po-lint
        id: po-lint
        run: |
          go run po-lint/po-lint.go
        shell: bash
      - name: output
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const output = `#### Pothetheus Operator Linting Results\`${{ steps.po-lint.outcome }}\``

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })
      
