name: pint

on:
  pull_request:
    paths:
    - kubectl_deploy/*/*promethus.yaml
    - kubectl_deploy/*/*promethus.yml
  workflow_dispatch:

jobs:
  pint:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Run po-linter
        continue-on-error: true
        id: po-linter
        run: |
          go run -v ./po-lint/po-linter.go
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
      - name: Result
        uses: actions/github-script@v6
        env:
            STDOUT: "${{ steps.po-linter.outputs.stdout }}"
            STDERR: "${{ steps.po-linter.outputs.stderr }}"
        with:
            github-token: ${{ secrets.ACTION_TOKEN }}
            script: |
                const output = `#### Prometheus Operator Linting Results\`${{ steps.po-linter.outcome }}\`

                <details><summary>Error</summary>

                \`\`\`${process.env.STDOUT}\`\`\`
                \`\`\`${process.env.STDERR}\`\`\`

                </details>

                *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })