name: Prometheus Operator Linter

on:
  pull_request:
    paths:
    - kubectl_deploy/*prometheus.yaml
    - kubectl_deploy/*prometheus.yml
    - kubectl_deploy/*/*prometheus.yaml
    - kubectl_deploy/*/*prometheus.yml
  workflow_dispatch:

jobs:
  po-lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run po-linter
        uses: docker://ministryofjustice/cloud-platform-po-linter:latest
        continue-on-error: true
        id: po-linter
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
          REPO_DIRECTORY: kubectl_deploy
          
      - name: Result
        uses: actions/github-script@v6
        env:
            summary: "Result:\n${{ steps.po-linter.outputs.po-linter }}"
        with:
            github-token: ${{ secrets.ACTION_TOKEN }}
            script: |
                const output = `#### Prometheus Operator Linting Results \`${{ steps.po-linter.outcome }}\`

                <details><summary>Show</summary>

                ${process.env.summary}

                </details>`

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })
      - name: Exitcode
        if: steps.po-linter.outcome != 'success'
        run: exit 1
