name: Shutdown EKS Sandbox
on:
#  schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '30 16 * * 3'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true

defaults:
  run:
    shell: bash

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
    
      - name: Run Terrafom destroy in infra/EKS
        run: | 
          git_dir=`git rev-parse --show-toplevel`
          #CONFIGURE TERRAFORM AND WORKSPACE
          bash infra/scripts/terraform-init.bash infra/EKS
          terraform -chdir="infra/EKS" workspace select sandbox
          bash infra/scripts/terraform-destroy.bash infra/EKS
      - uses: 8398a7/action-slack@v3
        name: Slack Success notification
        with:
          status: ${{ job.status }}
          fields: workflow,job,repo
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ success() }}
      - uses: 8398a7/action-slack@v3
        name: Slack Failure notification
        with:
          status: ${{ job.status }}
          fields: workflow,job,repo
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
        
