name: Terraform Plan infra/EKS
on:
  pull_request:
    paths:
    - infra/EKS/**
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true

jobs:  
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout     
        uses: actions/checkout@v4

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3.1.0
        with: 
          terraform_version: 1.0.1

      - id: terraform_fmt
        name: Run Terraform fmt on infra/EKS
        run: terraform -chdir="infra/EKS" fmt
      
      - id: terraform_init
        name: Run Terraform init on infra/EKS
        run: terraform -chdir="infra/EKS" init

      - id: terraform_workspace
        name: Select Sandbox Workspace
        run: terraform -chdir="infra/EKS" workspace select sandbox

      - id: terraform_validate
        name: Run Terraform Validate on infra/EKS
        run: terraform -chdir="infra/EKS" validate -no-color

      - id: terraform_plan
        name: Run Terraform plan on infra/EKS
        run: terraform -chdir="infra/EKS" plan -no-color -detailed-exitcode || true

      - name: Comment Output onto Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && steps.terraform_plan.outputs.exitcode == 2
        env:
            WORKSPACE: "terraform\n${{ steps.terraform_workspace.outputs.stdout }}"
            VALIDATE: "terraform\n${{ steps.terraform_validate.outputs.stdout }}"
            PLAN: "terraform\n${{ steps.terraform_plan.outputs.stdout }}"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const output = `#### Terraform Format and Style \`${{ steps.terraform_fmt.outcome }}\`
                #### Terraform Initialization \`${{ steps.terraform_init.outcome }}\`
                #### Terraform Workspace \`${{ steps.terraform_workspace.outcome }}\`

                <details><summary>Show</summary>
                
                \`\`\`${process.env.WORKSPACE}\`\`\`
                
                </details>

                #### Terraform Validate \`${{ steps.terraform_validate.outcome }}\`
                
                <details><summary>Show</summary>
                
                \`\`\`${process.env.VALIDATE}\`\`\`
                
                </details>

                #### Terraform Plan \`${{ steps.terraform_plan.outcome }}\`
                
                <details><summary>Show</summary>
                
                \`\`\`${process.env.PLAN}\`\`\`
                
                </details>

                *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })
      - name: Terraform Plan Status
        if: steps.terraform_plan.outputs.exitcode == 1
        run: exit 1
